layer.conf: make sure libdir can be seen by bitbake
Issue: LINCD-11570

This patch revert 66d1397bf[layer.conf: remove addpylib directive],
to make sure meta-intel/lib/oeqa can be seen by bitbake

This can fix oeqa test failure:
Exception: ImportError: Failed to import test module: dldt_inference_engine
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/layers/meta-intel/lib/oeqa/runtime/cases/dldt_inference_engine.py", line 4, in <module>
    from oeqa.runtime.miutils.targets.oeqatarget import OEQATarget
ModuleNotFoundError: No module named 'oeqa.runtime.miutils'

Upstream add this commit for compatible build meta-intel with OE-Core
kirkstone, wrlinux doesn't have this issue, so we can revert this
change, and have report this issue to upstream.

(LOCAL REV: NOT UPSTREAM) -- wrlinux specific

Signed-off-by: Changqing Li <changqing.li@windriver.com>